### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by CraftyClark** [mysidewalk/interview#4]
Link to data source in README.md file in the mysidewalk/interview/data-engineer directory appears to be broken. 

It currently links here -> https://github.com/mysidewalk/interview/blob/master/data-engineer/data.sfgov.org/Public-Safety/Fire-Department-Calls-for-Service/nuek-vuh3 

![image](https://user-images.githubusercontent.com/6503688/72567463-8e6f1980-387b-11ea-8a9a-a273dbe39de3.png)

**Comment by marr75** [comment]
Fixed by e63269a
